<template>
    <div>
        <Menu>
            <MenuButton>
                Options
            </MenuButton>
            <MenuItems>
                <MenuItem>
                    Settings
                </MenuItem>
                <MenuItem>
                    Calandar
                </MenuItem>
                <MenuItem>
                    Notes
                </MenuItem>
            </MenuItems>
        </Menu>
    </div>
</template>